config/routes.rb
Rails.application.routes.draw do

  get 'search' => 'search#search'
  namespace :admin do
    resources :customers
  end

#deviseでコントローラー名(customers)をつけて作っていたらコントローラーを変更する
#変更しないとdeviseコントローラーを使うことになる
  devise_for :customers, :controllers => {
 :registrations => 'customers/registrations',
 :sessions => 'customers/sessions',
 :passwords => 'customers/passwords'
}

  root 'home#top'

  namespace :admin do
    resources :customers
  end

  namespace :customer do
    resource :customers

    delete 'cart_items' => 'cart_items#destroy', as: 'cart_items'
    delete 'cart_items/:id' => 'cart_items#cancel', as:'cart_items_cancel'
    resources :cart_items, only: [:index, :new, :create, :update]

    resources :products, only: [:show, :index, :new, :create] do
      resources :comments ,only: [:create, :destroy]
    end

    #get 'orders/show' => 'orders#show'
    get 'orders/input' => 'orders#input'
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/done' => 'orders#done'
    resources :orders, only: [:index, :show, :create]
    resources :shippings, only: [:index, :create, :edit, :update, :destroy]
    resources :products, only: [:show, :index, :new, :create]
  end

  devise_for :admins

  get '/admin/top' => 'admin#top'

  get 'customer/customers/withdraw' => 'customer/customers#withdraw'

  get 'home/search/:genre_id' => 'home#search', as:'home_search'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
  	resources :products
  end


  namespace :admin do
  	resources :genres
  end

  namespace :admin do
    resources :orders
  end

  namespace :admin do
    resources :ordered_products, only: [:update]
  end

  get 'home/about' => 'home#about'

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.all.find(params[:id])
  end

  def edit
    @customer = Customer.all.find(params[:id])
  end

  def update
    @customer = Customer.all.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  def destroy
    @customer = Customer.all.find(params[:id])
    @customer.destroy
    redirect_to root_path
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :postal_code, :address, :phone_number, :customer_status, :deleted_at)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	before_action :authenticate_admin!
  def index
  	@orders = Order.all.page(params[:page]).per(10)#１ページ10件表示
  end

  def show
  	@order = Order.find(params[:id])
  	@ordered_products = @order.ordered_products
  	@total = 0
  	@ordered_products.each do |ordered_product|
  	@total += ordered_product.quantity * ordered_product.product_tax
  	end
  end

  def update
  	@order = Order.find(params[:id])
  	@ordered_products = @order.ordered_products
	@order.update(order_params)
  	if @order.read_attribute_before_type_cast(:order_status) == 1#1:入金確認したら製作ステータスを1:製作待ちにする
  		@ordered_products.each do |ordered_product|
  			ordered_product.update(production_status: 1)
  		end
  	end
  	redirect_to request.referer
  end

  private
  	def order_params
  		params.require(:order).permit(:order_status)
  	end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @carts = current_customer.cart_items

  end

  def create
    @cart = CartItem.find_by(customer_id: current_customer.id, product_id: params[:cart_item][:product_id] )
    if @cart
      @cart.quantity += params[:cart_item][:quantity].to_i
    else
      @cart = CartItem.new(cart_item_params)
      @cart.customer_id = current_customer.id
    end
    @cart.save
    redirect_to customer_cart_items_path
  end

  def update
    @cart = CartItem.find(params[:id])
    @cart.customer_id = current_customer.id
    @cart.update(cart_item_params)
    redirect_to customer_cart_items_path
  end

  def cancel #ルーティングを作成する先は:idを入れてasでルーティング名をつける
    @cart = CartItem.find(params[:id])
    @cart.destroy
    redirect_to customer_cart_items_path
  end

  def destroy
    @carts = current_customer.cart_items
    @carts.destroy_all
    redirect_to customer_products_path
  end


private
  def cart_item_params
    params.require(:cart_item).permit(:product_id, :quantity)
  end

end

app/controllers/customer/comments_controller.rb
class Customer::CommentsController < ApplicationController
	def create
		@product = Product.find(params[:product_id])
		@comment = current_customer.comments.new(comment_params)
		@comment.product_id = @product.id
		@comment.save
		@product_comments = @product.comments
		# if comment.save
		    #redirect_to customer_product_path(product.id)
		# else
			# @genres = Genre.all
			# @product = Product.find(params[:product_id])
        	# @quantity = CartItem.new
        	# @product_comment = Comment.new
        	# @product_comments = @product.comments
			# render 'customer/products/show'
		# end
	end

	def destroy
		@product = Product.find(params[:product_id])
		@comment = @product.comments.find(params[:id])
		@comment.destroy
		@product_comments = @product.comments
	end

	private
	def comment_params
		params.require(:comment).permit(:comment)
	end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!, only: [:show, :edit]

  def show
    @customer = current_customer
  end

  def edit
  	@customer = current_customer
  end

  def update
  	@customer = current_customer
    if @customer.update(customer_params)
      redirect_to customer_customers_path
    else
      render :edit
    end
  end

  def withdraw #退会ページ用
  end

  def destroy
  	customer = current_customer
    customer.update(customer_status: "退会済")
    reset_session
    redirect_to root_path
  end

  	private
	 def customer_params
	   params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number, :email, :customer_status, :deleted_at)
	 end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
    before_action :authenticate_customer!

    def index #注文履歴一覧画面(途中)
        @order = Order.where(customer_id: current_customer.id)
    end

    def show #注文履歴画面(途中)
        @order = Order.find(params[:id])
    end

    def create #注文の追加を保存
        @order = Order.new(collect_order)
        @order.save
        #カートアイテム全削除
       @carts = CartItem.where(customer_id: current_customer.id) 
        @carts.each do |carts|
            @ordered = OrderedProduct.new
            @ordered.order_id = @order.id
            @ordered.product_id = carts.product_id
            @ordered.quantity = carts.quantity
            @ordered.product_tax = carts.product.nontax * 1.1
            @ordered.save
        end
        @carts.destroy_all
        redirect_to customer_orders_done_path
    end

    def input #注文情報入力画面(途中)
        @customer = current_customer
        
    end

    def confirm #注文情報確認画面(途中)
        @shippings = Shipping.all
        @cart = CartItem.where(customer_id: current_customer.id)
        
        trigger = params[:trigger] #[自身=>A、登録済=>B、新規登録=>C]
        if trigger == 'C' #新しいお届け先
            @order = Order.new
            @shipping = Shipping.new
            @order.payment_method = params[:payment_method]
            @order.customer_id = current_customer.id
            @order.ordered_postal_code = params[:ordered_postal_code]
            @order.ordered_address = params[:ordered_address]
            @order.address_name = params[:address_name]
            @shipping.customer_id = current_customer.id
            @shipping.postal_code = params[:ordered_postal_code]
            @shipping.address = params[:ordered_address] 
            @shipping.name = params[:address_name]
            @shipping.save
            if ((@order.ordered_postal_code == "") || (@order.ordered_address == "") || (@order.address_name == ""))
                redirect_to customer_orders_input_path
            end
        elsif trigger == 'A' #ご自身の住所
            @order = Order.new
            @order.payment_method = params[:payment_method]
            @order.customer_id = current_customer.id
            @order.ordered_postal_code = current_customer.postal_code
            @order.ordered_address = current_customer.address
            @order.address_name = (current_customer.first_name + current_customer.last_name)
        elsif trigger == 'B' #登録済の住所
            @order = Order.new
            @order.customer_id = current_customer.id
            @order.payment_method = params[:payment_method]
            @order.ordered_postal_code = Shipping.find(params[:address_id]).postal_code
            @order.ordered_address = Shipping.find(params[:address_id]).address
            @order.address_name = Shipping.find(params[:address_id]).name
        end
    end

    def done #注文完了画面(OK)
    end

    private
      def collect_order
        params.require(:order).permit(:ordered_postal_code, :ordered_address, :address_name, :shipping_cost, :total_price, :payment_method, :order_status, :customer_id)
      end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
    #商品一覧ページ
    def index
        #product.allにページネーション実装(1ページ8件)
        @products = Product.where(sales_status: 0).page(params[:page]).per(8)
        #, Product.genres.genre_status: 0
        @genres = Genre.where(genre_status: 0)
    end
    
    #商品詳細ページ
    def show
        @genres = Genre.where(genre_status: 0)
        @product = Product.find(params[:id])
        @quantity = CartItem.new
        @product_comment = Comment.new
        @product_comments = @product.comments
    end
    
    #（仮）カートへ追加する数量を送信
    def create
        @quantity = Product.new(product_params)
    end

    private

    def product_params
        params.require(:product).permit(:image, :product_name, :explanation, :genre_id, :nontax, :sales_status)
    end
end

app/controllers/customer/shippings_controller.rb
class Customer::ShippingsController < ApplicationController
    def index
        @shippings = Shipping.where(customer_id: current_customer.id)
        @shipping = Shipping.new
    end

    def create
        @shipping = Shipping.new(shipping_params)
        @shipping.customer_id = current_customer.id
        if @shipping.save
            redirect_to customer_shippings_path
        else
            render :index
        end
    end

    def edit
        @shipping = Shipping.find(params[:id])
    end

    def update
        @shipping = Shipping.find(params[:id])
        @shipping.customer_id = current_customer.id
        if @shipping.update(shipping_params)
            redirect_to customer_shippings_path
        else
            render :edit
        end
    end

    def destroy
        @shipping = Shipping.find(params[:id])
        @shipping.destroy
        redirect_to customer_shippings_path
    end

    private
        def shipping_params
            params.require(:shipping).permit(:postal_code, :address, :name)
        end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < DeviseController
#deviseのgit hubから継承しました→hubhttps://github.com/heartcombo/devise/blob/master/app/controllers/devise/passwords_controller.rb

  # Render the #edit only if coming from a reset password email link
  # append_before_action :assert_reset_token_passed, only: :edit

  # GET /resource/password/new
  def new
    self.resource = resource_class.new
  end

  # POST /resource/password
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    self.resource = resource_class.new
    set_minimum_password_length
    resource.reset_password_token = params[:reset_password_token]
  end

  # PUT /resource/password
  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    yield resource if block_given?

    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      if Devise.sign_in_after_reset_password
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        set_flash_message!(:notice, flash_message)
        resource.after_database_authentication
        sign_in(resource_name, resource)
      else
        set_flash_message!(:notice, :updated_not_active)
      end
      respond_with resource, location: after_resetting_password_path_for(resource)
    else
      set_minimum_password_length
      respond_with resource
    end
  end

  protected
    def after_resetting_password_path_for(resource)
      Devise.sign_in_after_reset_password ? after_sign_in_path_for(resource) : new_session_path(resource_name)
    end

    # The path used after sending reset password instructions
    def after_sending_reset_password_instructions_path_for(resource_name)
      new_session_path(resource_name) if is_navigational_format?
    end

    #pretend は消した

    # Check if a reset_password_token is provided in the request

    # Check if proper Lockable module methods are present & unlock strategy
    # allows to unlock resource on password reset
    def unlockable?(resource)
      resource.respond_to?(:unlock_access!) &&
        resource.respond_to?(:unlock_strategy_enabled?) &&
        resource.unlock_strategy_enabled?(:email)
    end

    def translation_scope
      'devise.passwords'
    end
end

app/controllers/customers/products_controller.rb
class Customers::ProductsController < ApplicationController
    #商品一覧ページ
    def index
        #product.allにページネーション実装(1ページ8件)
        @products = Product.all.page(params[:page]).per(8)
    end
    
    #商品詳細ページ
    def show
        @product = Product.find(params[:id])
        @quantity = admin/Ordered_product.new
    end
    
    #（仮）カートへ追加する数量を送信
    def create
        @quantity = Product.new(product_params)
    end

    private

    def product_params
        params.require(:product).permit(:image, :product_name, :explanation, :genre_id, :nontax, :sales_status)
    end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/views/customer/orders/confirm.html.erb
<div class="container">
    <h3><span class="headline-confirm">注文情報確認</span></h3>
    <div class="row">
        <div class="col-xs-7">
            <table class="table table-line-a">
                <thead>
                    <tr>
                        <td class="active">商品名</td>
                        <td class="active">単価（税込）</td>
                        <td class="active">数量</td>
                        <td class="active">小計</td>
                    </tr>
                </thead>
                <tbody>
                    <% @total = 0 %>
                    <% @cart.each do |cart| %>
                        <% @tanka = cart.product.nontax * 1.1 %>
                        <% @total += @tanka * cart.quantity %>
                        <tr>
                            <td class="vertical-align"><%= attachment_image_tag(cart.product, :image, fallback: "no_image.jpg", size: "60x60") %>　<%= cart.product.product_name %></td>
                            <td class="vertical-align"><%= @tanka.round.to_s(:delimited) %></td>
                            <td class="vertical-align"><%= cart.quantity %></td>
                            <td class="vertical-align"><%= (@tanka * cart.quantity).round.to_s(:delimited) %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>

        <div class="col-xs-3">
            <table class="table table-line-a">
                <tr>
                    <td class="active">送料</td>
                    <td><%= @order.shipping_cost %></td>
                </tr>
                <tr>
                    <td class="active">商品合計</td>
                    <td><%= @total.round.to_s(:delimited) %></td>
                </tr>
                <tr>
                    <td class="active">請求金額</td>
                    <td><%= (@total + @order.shipping_cost).round.to_s(:delimited) %></td>
                </tr>
            </table>
        </div>
        <div class="col-xs-2"></div>
    </div>

    <div class="row">
        <div class="col-xs-9">
            <ul>
                <li><span class="title">支払方法　</span>
                    <%= @order.payment_method %></li>
            </ul><br>
            <ul>
                <li><span class="title">お届け先　</span>
                    <%= @order.ordered_postal_code %>　<%= @order.ordered_address %><br>
                    　　　　　 <%= @order.address_name %></li>
            </ul>
        </div>
        <div class="col-xs-3">
        </div>
    </div>

    <div class="row">
        <%# <div class="col-xs-4"></div> %>
        <div class="col-xs-offset-5 col-xs-2">
        <%= form_for @order,url:customer_orders_path do |f| %>
            <%= f.hidden_field :ordered_postal_code, :value => @order.ordered_postal_code %>
            <%= f.hidden_field :ordered_address, :value => @order.ordered_address %>
            <%= f.hidden_field :address_name, :value => @order.address_name %>
            <%= f.hidden_field :shipping_cost, :value => @order.shipping_cost %>
            <%= f.hidden_field :total_price, :value => @total %>
            <%= f.hidden_field :payment_method, :value => @order.payment_method %>
            <%= f.hidden_field :order_status, :value => @order.order_status %>
            <%= f.hidden_field :customer_id, :value => current_customer.id %>

            <%= f.submit "　購入を確定する　", class: "btn btn-success", style: "color: white;"  %>

        <% end %>
        </div>
        <%# <div class="col-xs-4"></div> %>
    </div>
</div>

app/views/customer/orders/done.html.erb
<div class="row">
    <div class="final-box col-xs-offset-3 col-xs-6">
        <p>ご購入ありがとうございました！</p>
    </div>   
</div>

app/views/customer/orders/index.html.erb
<h3 class="headline-a">注文履歴一覧</h3>
<div class="row">
    <div class="col-xs-offset-1 col-xs-10">
        <table class="table table-line">
            <thead>
                <tr>
                    <th class="active">注文日</th>
                    <th class="active">配送先</th>
                    <th class="active">注文商品</th>
                    <th class="active">支払金額</th>
                    <th class="active">ステータス</th>
                    <th class="active">注文詳細</th>
                </tr>
            </thead>

            <tbody>
                <% @order.each do |order| %>
                    <tr>
                        <td class="vertical-align"><%= order.created_at.strftime('%Y/%m/%d') %></td>
                        <td class="vertical-align"><%= order.ordered_postal_code %><br>
                            <%= order.ordered_address %><br>
                            <%= order.address_name %></td>
                        <td class="vertical-align"><% order.ordered_products.each do |ordered_product| %>
                          <%= ordered_product.product.product_name %><br>
                        <% end %></td>
                        <td class="vertical-align"><%= (order.total_price + order.shipping_cost).round.to_s(:delimited) %>円</td>
                        <td class="vertical-align"><%= order.order_status %></td>
                        <td class="table-align tate-tate vertical-align"><%= link_to " 表示する ", customer_order_path(order.id), class: "btn btn-primary btn-sm", style: "color: white;" %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/customer/orders/input.html.erb
<div class="order-wapper">
    <%= form_with url: customer_orders_confirm_path, method: :get, local: true do |f| %> 
        <h3 class="headline-a"><span class="#">注文情報入力</span></h3><br>
        <%# 支払い方法box %>
        <span class="headline-cache">支払方法</span>
        <div class="box-box">
            <%= f.radio_button :payment_method, :クレジットカード, {:checked => true} %>
            <%= f.label :クレジット %><br>
            <%= f.radio_button :payment_method, :銀行振込 %>
            <%= f.label :銀行振込 %>
        </div>
        <%# お届け先box %>
        <div class="address-method">
            <span class="headline-cache">お届け先</span>
            <div class="box-box">
                <%# ご自身の住所 %>
                <%= f.radio_button :trigger, 'A', {:checked => true} %>
                <%= f.label :ご自身の住所 %><br>
                <div class="box-in-box">
                    <%= @customer.postal_code %>
                    <%= @customer.address %><br>
                    <%= (@customer.first_name) + (@customer.last_name) %>
                </div><br>

                <%# 登録済の住所 %>
                <%= f.radio_button :trigger, 'B' %>
                <%= f.label :登録済住所から選択 %><br>
                <div class="box-in-box"> 
                    <%= f.collection_select :address_id, Shipping.where(customer_id: current_customer.id), :id, :full_order_address, include_blank: "選択して下さい" %>
                </div><br>

                <%# 新規登録住所 %>
                <%= f.radio_button :trigger, 'C' %>
                <%= f.label :新しいお届け先 %>
                <div class="box-in-box">
                <table>
                    <tr>
                        <td><%= f.label :郵便番号（ハイフンなし） %></td>
                        <td><%= f.text_field :ordered_postal_code, autofocus: true %></td>
                    </tr>
                    <tr>
                        <td><%= f.label :住所 %></td>
                        <td><%= f.text_field :ordered_address, autofocus: true %></td>
                    </tr>
                    <tr>
                        <td><%= f.label :宛名 %></td>
                        <td><%= f.text_field :address_name, autofocus: true %></td>
                    </tr>
                </table></div>
            </div>
        </div><br>
        
        <div class="row">
            <div class="col-xs-offset-5 col-xs-2">
                <%= f.submit "確認画面へ進む", class: "btn btn-success", style: "color: white;"  %>
            </div>
        </div>
        
    <% end %>
</div>

app/views/customer/orders/show.html.erb
<div class="container">
    <h3><span>注文履歴一覧</span></h3>
    <div class="row">
        <div class="col-xs-6">
            <h5><span class="small-headline">注文情報</span></h5>
            <table class="table table-line-a">
                <tr>
                    <td class="active">注文日</td>
                    <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
                </tr>
                <tr>
                    <td class="active">配送先</td>
                    <td><%= @order.ordered_postal_code %><br>
                        <%= @order.ordered_address %><br>
                        <%= @order.address_name %></td>
                </tr>
                <tr>
                    <td class="active">支払方法</td>
                    <td><%= @order.payment_method %></td>
                </tr>
                <tr>
                    <td class="active">ステータス</td>
                    <td><%= @order.order_status %> </td>
                </tr>
            </table>
        </div>
        <div class="col-xs-3">
            <h5><span class="small-headline">請求金額</span></h5>
            <table class="table table-line-a">
                <tr>
                    <td class="active">商品合計</td>
                    <td><%= @order.total_price.round.to_s(:delimited) %></td>
                </tr>
                <tr>
                    <td class="active">配送料</td>
                    <td><%= @order.shipping_cost %></td>
                </tr>
                <tr>
                    <th class="active">ご請求額</th>
                    <td><%= (@order.total_price + @order.shipping_cost).round.to_s(:delimited) %></td>
                </tr>
            </table>
        </div>
        <div class="col-xs-3"></div>
    </div><br>

    <div class="row">
        <div class="col-xs-8">
            <h5><span class="small-headline">注文内容</span></h5>
            <table class="table table-line-a">
                <thead>
                    <tr>
                        <td class="active">商品</td>
                        <td class="active">単価（税込）</td>
                        <td class="active">個数</td>
                        <td class="active">小計</td>
                    </tr>
                </thead>
                <tbody>
                    <% @order.ordered_products.each do |ordered_product| %>
                    <tr>
                        <td><%= ordered_product.product.product_name %></td>
                        <td><%= ordered_product.product_tax.round.to_s(:delimited) %></td>
                        <td><%= ordered_product.quantity %></td>
                        <td><%= (ordered_product.product_tax * ordered_product.quantity).round.to_s(:delimited) %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-xs-4">
        </div>
    </div>
</div>