config/routes.rb
Rails.application.routes.draw do

  get 'search' => 'search#search'
  namespace :admin do
    resources :customers
  end

#deviseでコントローラー名(customers)をつけて作っていたらコントローラーを変更する
#変更しないとdeviseコントローラーを使うことになる
  devise_for :customers, :controllers => {
 :registrations => 'customers/registrations',
 :sessions => 'customers/sessions',
 :passwords => 'customers/passwords'
}

  root 'home#top'

  namespace :admin do
    resources :customers
  end

  namespace :customer do
    resource :customers

    delete 'cart_items' => 'cart_items#destroy', as: 'cart_items'
    delete 'cart_items/:id' => 'cart_items#cancel', as:'cart_items_cancel'
    resources :cart_items, only: [:index, :new, :create, :update]

    resources :products, only: [:show, :index, :new, :create] do
      resources :comments ,only: [:create, :destroy]
    end

    #get 'orders/show' => 'orders#show'
    get 'orders/input' => 'orders#input'
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/done' => 'orders#done'
    resources :orders, only: [:index, :show, :create]
    resources :shippings, only: [:index, :create, :edit, :update, :destroy]
    resources :products, only: [:show, :index, :new, :create]
  end

  devise_for :admins

  get '/admin/top' => 'admin#top'

  get 'customer/customers/withdraw' => 'customer/customers#withdraw'

  get 'home/search/:genre_id' => 'home#search', as:'home_search'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
  	resources :products
  end


  namespace :admin do
  	resources :genres
  end

  namespace :admin do
    resources :orders
  end

  namespace :admin do
    resources :ordered_products, only: [:update]
  end

  get 'home/about' => 'home#about'

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordered_products, dependent: :destroy
  enum payment_method: {クレジットカード: 0,銀行振込: 1}
  enum order_status: {入金待ち: 0,入金確認: 1,製作中: 2,発送準備中: 3,発送済み: 4}
  validates :ordered_postal_code,presence: true
  validates :ordered_address,presence: true
  validates :address_name,presence: true
  validates :payment_method,presence: true
  def full_ordered
    self.ordered_postal_code + "/" + self.ordered_address + "/" + self.address_name
  end  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	before_action :authenticate_admin!
  def index
  	@orders = Order.all.page(params[:page]).per(10)#１ページ10件表示
  end

  def show
  	@order = Order.find(params[:id])
  	@ordered_products = @order.ordered_products
  	@total = 0
  	@ordered_products.each do |ordered_product|
  	@total += ordered_product.quantity * ordered_product.product_tax
  	end
  end

  def update
  	@order = Order.find(params[:id])
  	@ordered_products = @order.ordered_products
	@order.update(order_params)
  	if @order.read_attribute_before_type_cast(:order_status) == 1#1:入金確認したら製作ステータスを1:製作待ちにする
  		@ordered_products.each do |ordered_product|
  			ordered_product.update(production_status: 1)
  		end
  	end
  	redirect_to request.referer
  end

  private
  	def order_params
  		params.require(:order).permit(:order_status)
  	end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
    before_action :authenticate_customer!

    def index #注文履歴一覧画面(途中)
        @order = Order.where(customer_id: current_customer.id)
    end

    def show #注文履歴画面(途中)
        @order = Order.find(params[:id])
    end

    def create #注文の追加を保存
        @order = Order.new(collect_order)
        @order.save
        #カートアイテム全削除
       @carts = CartItem.where(customer_id: current_customer.id) 
        @carts.each do |carts|
            @ordered = OrderedProduct.new
            @ordered.order_id = @order.id
            @ordered.product_id = carts.product_id
            @ordered.quantity = carts.quantity
            @ordered.product_tax = carts.product.nontax * 1.1
            @ordered.save
        end
        @carts.destroy_all
        redirect_to customer_orders_done_path
    end

    def input #注文情報入力画面(途中)
        @customer = current_customer
        
    end

    def confirm #注文情報確認画面(途中)
        @shippings = Shipping.all
        @cart = CartItem.where(customer_id: current_customer.id)
        
        trigger = params[:trigger] #[自身=>A、登録済=>B、新規登録=>C]
        if trigger == 'C' #新しいお届け先
            @order = Order.new
            @shipping = Shipping.new
            @order.payment_method = params[:payment_method]
            @order.customer_id = current_customer.id
            @order.ordered_postal_code = params[:ordered_postal_code]
            @order.ordered_address = params[:ordered_address]
            @order.address_name = params[:address_name]
            @shipping.customer_id = current_customer.id
            @shipping.postal_code = params[:ordered_postal_code]
            @shipping.address = params[:ordered_address] 
            @shipping.name = params[:address_name]
            @shipping.save
            if ((@order.ordered_postal_code == "") || (@order.ordered_address == "") || (@order.address_name == ""))
                redirect_to customer_orders_input_path
            end
        elsif trigger == 'A' #ご自身の住所
            @order = Order.new
            @order.payment_method = params[:payment_method]
            @order.customer_id = current_customer.id
            @order.ordered_postal_code = current_customer.postal_code
            @order.ordered_address = current_customer.address
            @order.address_name = (current_customer.first_name + current_customer.last_name)
        elsif trigger == 'B' #登録済の住所
            @order = Order.new
            @order.customer_id = current_customer.id
            @order.payment_method = params[:payment_method]
            @order.ordered_postal_code = Shipping.find(params[:address_id]).postal_code
            @order.ordered_address = Shipping.find(params[:address_id]).address
            @order.address_name = Shipping.find(params[:address_id]).name
        end
    end

    def done #注文完了画面(OK)
    end

    private
      def collect_order
        params.require(:order).permit(:ordered_postal_code, :ordered_address, :address_name, :shipping_cost, :total_price, :payment_method, :order_status, :customer_id)
      end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-offset-2 col-xs-8">
			<h3><span>　注文履歴一覧　</span></h3><br><br>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-offset-2 col-xs-8">
		<table class = "table table-hover table-inverse">
			<thead>
				<tr class="active">
					<th>購入日</th>
					<th>購入者</th>
					<th>注文個数</th>
					<th>注文ステータス</th>
				</tr>
			</thead>
			<tbody style="background-color: rgba(255, 255, 255, 0.3);">
				<% @orders.each do |order| %>
					<tr>
						<td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order) %></td>
						<td><%= order.customer.first_name %><%= order.customer.last_name %></td>
						<% @totalquantity = 0 %>
						<% order.ordered_products.each do |ordered_product| %>
  	 						<% @totalquantity += ordered_product.quantity %>
  						<% end %>
  						<td><%= @totalquantity %></td>
						<td><%= order.order_status %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
		<div class="col-xs-offset-5 col-xs-6"><%= paginate @orders %></div>
	</div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-offset-2 col-xs-8">
			<h3><span>　注文履歴詳細　</span></h3><br><br>
		</div>
	</div>

	<div class="row">
		<table>
			<tr>
				<th>購入者</th>
					<th><%= @order.customer.first_name %>　<%= @order.customer.last_name %></th>
			</tr>
			<tr>
				<th>配送先</th>
					<th>〒<%= @order.ordered_postal_code %>　<%= @order.ordered_address %><br>
						<%= @order.address_name %>
					</th>
			</tr>
			<tr>
				<th>支払方法</th>
					<th><%= @order.payment_method %></th>
			</tr>
			<tr>
				<th>注文ステータス</th>
					<th><%= form_for @order,url:admin_order_path(@order) do |f| %>
					<%= f.select  :order_status, [["入金待ち", "入金待ち"],["入金確認","入金確認"],["製作中","製作中"],["発送準備中","発送準備中"],["発送済み","発送済み"]] %>
					<%= f.submit '更新', class: "btn btn-primary", style: "color: white;"  %>
					</th>
					<% end %>
			</tr>
		</table>
	</div>
	<div class="row">
		<div class="col-xs-9">
		<table class = "table table-hover table-inverse">
			<thead>
				<tr class="active">
					<th>商品名</th>
					<th>単価（税込）</th>
					<th>数量</th>
					<th>小計</th>
					<th>制作ステータス</th>
				</tr>
			</thead>
			<tbody style="background-color: rgba(255, 255, 255, 0.3);">
				<% @ordered_products.each do |ordered_products| %>
					<tr>
						<td><%= ordered_products.product.product_name %></td>
						<td><%= ordered_products.product_tax .to_s(:delimited) %></td>
						<td><%= ordered_products.quantity %></td>
						<td><%= (ordered_products.quantity * ordered_products.product_tax) .to_s(:delimited) %></td>
						<td>
							<%= form_for ordered_products,url:admin_ordered_product_path(ordered_products.id) do |f| %>
							<%= f.select  :production_status, [["着手不可", "着手不可"],["製作待ち","製作待ち"],["製作中","製作中"],["製作完了","製作完了"]] %>
							<%= f.submit '更新', class: "btn btn-primary", style: "color: white;"  %>
							<% end %>
						</td>

					</tr>
				<% end %>
			</tbody>
		</table>
		</div>
		
		<div class="col-xs-3">
			<table>
			<tr>
				<th>商品合計</th>
					<th>　<%= @total .to_s(:delimited) %></th>
			</tr>
			<tr>
				<th>送料</th>
					<th>　<%= @order.shipping_cost .to_s(:delimited) %></th>
			</tr>
			<tr>
				<th>請求合計金額</th>
					<th>　<%= (@total+@order.shipping_cost) .to_s(:delimited) %></th>
			</tr>
			</table>
		</div>
	</div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>