config/routes.rb
Rails.application.routes.draw do

  get 'search' => 'search#search'
  namespace :admin do
    resources :customers
  end

#deviseでコントローラー名(customers)をつけて作っていたらコントローラーを変更する
#変更しないとdeviseコントローラーを使うことになる
  devise_for :customers, :controllers => {
 :registrations => 'customers/registrations',
 :sessions => 'customers/sessions',
 :passwords => 'customers/passwords'
}

  root 'home#top'

  namespace :admin do
    resources :customers
  end

  namespace :customer do
    resource :customers

    delete 'cart_items' => 'cart_items#destroy', as: 'cart_items'
    delete 'cart_items/:id' => 'cart_items#cancel', as:'cart_items_cancel'
    resources :cart_items, only: [:index, :new, :create, :update]

    resources :products, only: [:show, :index, :new, :create] do
      resources :comments ,only: [:create, :destroy]
    end

    #get 'orders/show' => 'orders#show'
    get 'orders/input' => 'orders#input'
    get 'orders/confirm' => 'orders#confirm'
    get 'orders/done' => 'orders#done'
    resources :orders, only: [:index, :show, :create]
    resources :shippings, only: [:index, :create, :edit, :update, :destroy]
    resources :products, only: [:show, :index, :new, :create]
  end

  devise_for :admins

  get '/admin/top' => 'admin#top'

  get 'customer/customers/withdraw' => 'customer/customers#withdraw'

  get 'home/search/:genre_id' => 'home#search', as:'home_search'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
  	resources :products
  end


  namespace :admin do
  	resources :genres
  end

  namespace :admin do
    resources :orders
  end

  namespace :admin do
    resources :ordered_products, only: [:update]
  end

  get 'home/about' => 'home#about'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :product
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :customer
	belongs_to :product
	validates :comment, presence: true, length: {maximum: 100}
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, format: {with: /\A[0-9]{7}\z/} #7桁の数字のみ有効
  validates :address, presence: true
  validates :phone_number, presence: true,format: {with: /\A\d{10,11}\z/} #10桁or11桁の数字のみ有効

  has_many :cart_items, dependent: :destroy
  has_many :shippings, dependent: :destroy
  enum customer_status:{ 有効: 0, 退会済: 1}

  #acts_as_paranoid #paranoiaはいらない（enumの切り替えだけでいい）

  has_many :comments, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :products, dependent: :destroy
	enum genre_status: {有効: 0, 無効: 1}
	
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordered_products, dependent: :destroy
  enum payment_method: {クレジットカード: 0,銀行振込: 1}
  enum order_status: {入金待ち: 0,入金確認: 1,製作中: 2,発送準備中: 3,発送済み: 4}
  validates :ordered_postal_code,presence: true
  validates :ordered_address,presence: true
  validates :address_name,presence: true
  validates :payment_method,presence: true
  def full_ordered
    self.ordered_postal_code + "/" + self.ordered_address + "/" + self.address_name
  end  
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
	belongs_to :order
	belongs_to :product
	enum production_status: {着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了:3}
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :cart_items,  dependent: :destroy
	has_many :ordered_products, dependent: :destroy
	belongs_to :genre
	attachment :image
	enum sales_status: {販売中: 0, 売切れ: 1}
	has_many :comments, dependent: :destroy

end

app/models/shipping.rb
class Shipping < ApplicationRecord
    belongs_to :customer
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
    def full_order_address
        self.postal_code + "/" + self.address + "/" + self.name
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?


	def after_sign_up_path_for(resource)
    	if customer_signed_in?
      	  root_path
      	elsif admin_signed_in?
      	  '/admin/top'
      	end
	end

	def after_sign_in_path_for(resource)
      if admin_signed_in?
        '/admin/top'
      elsif current_customer.customer_status == "退会済"
         flash[:notice] = "退会済みです"
         sign_out current_customer
         new_customer_session_path
      elsif customer_signed_in?
          root_path
      end
	end

	def after_sign_out_path_for(resource_or_scope)
		if resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
	end


protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name,:first_name_kana,:last_name_kana, :email, :postal_code, :address, :postal_code, :phone_number, :customer_status])
    end

   def require_no_authentication
   end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
    @products = Product.where(sales_status: 0).page(params[:page]).per(8).order(created_at: "DESC")
  	@product = Product.find(Comment.group(:product_id).order('count(product_id) desc').limit(4).pluck(:product_id))
  	@genres = Genre.where(genre_status: 0)
  end

  def search
  	@genres = Genre.where(genre_status: 0)
	  @products = Product.where(genre_id: params[:genre_id].to_i, sales_status: 0).page(params[:page]).per(8)
    @genre = Genre.find(params[:genre_id])
  end

  def about
    
  end

protected

  def product_params
    params.require(:product).permit(:image, :product_name, :explanation, :genre_id, :nontax, :sales_status)
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    #商品一覧ページ
    def index
        #product.allにページネーション実装(1ページ8件)
        @products = Product.all.page(params[:page]).per(8)
    end
    
    #商品詳細ページ
    def show
        #@product = Product.find(params[:id])
    end
    
    #（仮）カートへ追加する数量を送信
    def create
        @quantity = Product.new(product_params)
    end

    private

    def product_params
        params.require(:product).permit(:nontax)
    end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="contanier-fluid">
  <div class="row">
  	<div class="shop-info col-xs-offset-2 col-xs-8">
      <div class="info-header">
        <h3 style="display: inline-block;">店舗情報</h3>
      </div>
    </div>
  </div>

  <div class="row">
  	<div class="col-xs-offset-2 col-xs-8">
  		<div class="col-xs-4">
  			<div class="shop-image"></div>
  		</div>
  		<div class="col-xs-8">
  			<table class="info-body">
  				<tr>
  					<td class="info-index">営業時間</td>
  					<td class="info-content">11:00~19:00</td>
  				</tr>
  				<tr>
  					<td class="info-index">定休日</td>
  					<td class="info-content">なし</td>
  				</tr>
  				<tr>
  					<td class="info-index">住所</td>
  					<td class="info-content">〒389-0102 長野県北佐久郡軽井沢町大字軽井沢1178</td>
  				</tr>
  				<tr>
  					<td class="info-index">電話番号</td>
  					<td class="info-content">0267-42-4754</td>
  				</tr>
  				<tr>
  					<td class="info-index">ひとこと</td>
  					<td class="info-content">近隣のみなさまに愛されるケーキ屋さんを目指して、2020年4月1日にオープンしました</br>
  					旬のフルーツをふんだんに使ったケーキをたくさんご用意しています</br>
  				    気軽にお立ち寄りください
  				　　</td>
  				</tr>
  			</table>
  		</div>
  	</div>
  </div>

<div class="row">
	<div class="col-xs-offset-2 col-xs-8">
		<div id='map'></div>
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAKcYN2WnO0N2j4ATcWVi09tSCqdcqOO0Q&callback=initMap" async defer></script>
		</div>
    </div>
</div>

app/views/home/search.html.erb
<div class="row">

	<div class="col-xs-3">
    	<%= render 'layouts/searchform' %>
  	</div>

	<div class="col-xs-9">
		<%= render 'customer/products/index', products: @products, genre: @genre %>
	</div>

</div>

app/views/home/top.html.erb
<div class="row">

	<div class="col-xs-3">
    <%= render 'layouts/searchform' %>
  </div>

	<div class="col-xs-9">

    <div class="row">
  		<div class="top_wrapper">
  			<div class="welcome_message">
  				<p>ようこそ、NaganoCakeへ！</p>
  				<p>このサイトは、ケーキ販売のECサイトになります。</p>
  				<p>会員でない方も商品の閲覧はできますが、</p>
  				<p>購入には会員登録が必要になります。</p>
  			</div>
        <div class="skippr">
         <div style="background-image: url(<%= asset_path('apple_cake.png') %>)"></div>
         <div style="background-image: url(<%= asset_path('donut.jpeg') %>)"></div>
         <div style="background-image: url(<%= asset_path('Macaroons.jpeg') %>)"></div>
        </div>
  		</div>
    </div>

    <div class="row">
  		<h2 class="recomend-headline" style="display: inline-block; border-bottom: double;">オススメ商品</h2>
      <div class="recomend-box">
      <% @products.first(4).each do |product| %>
      <%= link_to customer_product_path(product) do %>
      <ul class="recomend-items" style="width: 200px;">
        <li class="recomend-photo"><%= attachment_image_tag product, :image, fallback: 'no_image.jpg', size: '150x150', class: "rounded" %></li>
        <li class="recomend-name"><%= product.product_name %></li>
        <li class="recomend-price">¥ <%= (product.nontax * 1.1).floor.to_s(:delimited) %></li>
        <% end %>
      </ul>
      <% end %>
    </div>
    </div>

    <div class="row">
      <h2 class="popular-headline" style="display: inline-block; border-bottom: double;">人気商品</h2>
      <div class="popular-box">
      <% @product.each do |product| %>
        <% if product.genre.genre_status == "有効" %>
          <%= link_to customer_product_path(product) do %>
            <ul class="popular-items" style="width: 200px;">
              <li class="popular-photo"><%= attachment_image_tag product, :image, fallback: 'no_image.jpg', size: '150x150', class: "rounded" %></li>
              <li class="popular-name"><%= product.product_name %></li>
              <li class="popular-price">¥ <%= (product.nontax * 1.1).floor.to_s(:delimited) %></li>
          <% end %>
        </ul>
        <% end %>
      <% end %>
    </div>
    </div>

  </div>

  </div>

</div>